#!/usr/bin/env python3
"""
generate_valiantwrapped_site.py
(Option A: Static “browse” homepage + authors.json + Spotify-ish UI)

What this version adds (on top of your current script):
- Generates docs/data/authors.json (1 record per author)
- Replaces the simple <ul> index with a Spotify-ish browse page:
  - grid of “artist cards”
  - search box
  - optional theme filter (only shows if themes exist in your CSV)
- Writes docs/assets/styles.css + docs/assets/app.js used by the browse page
- Keeps your existing author pages and cover-copy safety logic
"""

import os
import re
import shutil
import pandas as pd
from pathlib import Path
import html as html_lib
from datetime import datetime
import json

# ----------------------------
# PATHS (relative to this script)
# ----------------------------

BASE_DIR = Path(__file__).resolve().parent

SUMMARY_FILE = BASE_DIR / "author_summary_2025_present_test.csv"
PERSONA_FILE = BASE_DIR / "outputs" / "author_music_personas.csv"

# Album cover inputs (generated by generate_album_covers.py)
ALBUM_COVERS_SRC_DIR = BASE_DIR / "outputs" / "album_covers"

# GitHub Pages publish dir
DOCS_DIR = BASE_DIR / "docs"
AUTHOR_DIR = DOCS_DIR / "authors"

# Assets (covers + browse UI)
ASSETS_DIR = DOCS_DIR / "assets"
COVERS_DIR = ASSETS_DIR / "album_covers"     # keeps your current cover location
BROWSE_ASSET_DIR = ASSETS_DIR                # where styles.css + app.js will live

DATA_DIR = DOCS_DIR / "data"                 # authors.json goes here

# ----------------------------
# REBUILD (SAFE MODE)
# ----------------------------

def rebuild_docs_folder():
    if DOCS_DIR.exists():
        shutil.rmtree(DOCS_DIR)
    AUTHOR_DIR.mkdir(parents=True, exist_ok=True)
    COVERS_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    BROWSE_ASSET_DIR.mkdir(parents=True, exist_ok=True)

rebuild_docs_folder()

# ----------------------------
# LOAD DATA
# ----------------------------

summary_df = pd.read_csv(SUMMARY_FILE)
persona_df = pd.read_csv(PERSONA_FILE)

build_report = []  # list of (author_label, issue, details)

# ----------------------------
# HELPERS
# ----------------------------

def now_iso() -> str:
    return datetime.now().isoformat(timespec="seconds")

def canonical_author_label(value: str) -> str:
    """
    Convert values like:
      'Kim_Michael_58290603100.csv'
      'author_csvs/Kim_Michael_58290603100.csv'
    into:
      'Kim_Michael_58290603100'
    """
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ""
    s = str(value).strip()
    s = os.path.basename(s)
    s = s.replace("\\", "/")
    if s.lower().endswith(".csv"):
        s = s[:-4]
    if s.lower().endswith(".txt"):
        s = s[:-4]
    return s.strip()

def parse_author_name(label: str):
    parts = label.split("_")
    last = parts[0] if len(parts) > 0 else ""
    first = parts[1] if len(parts) > 1 else ""
    return first, last

def display_name_from_label(label: str) -> str:
    first, last = parse_author_name(label)
    name = f"{first} {last}".strip()
    return name if name else label

def safe_split_themes(x) -> list[str]:
    """
    Supports themes in formats like:
      "Theme A; Theme B; Theme C"
      "Theme A, Theme B, Theme C"
      ["Theme A","Theme B"] (stringified JSON-ish)
    If you don't have themes, returns [].
    """
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return []
    s = str(x).strip()
    if not s:
        return []
    # try JSON array
    if s.startswith("[") and s.endswith("]"):
        try:
            arr = json.loads(s)
            if isinstance(arr, list):
                return [str(t).strip() for t in arr if str(t).strip()]
        except Exception:
            pass
    # split by common delimiters
    if ";" in s:
        parts = [p.strip() for p in s.split(";")]
    else:
        parts = [p.strip() for p in s.split(",")]
    return [p for p in parts if p]

def format_tracklist(tracklist) -> str:
    if tracklist is None or (isinstance(tracklist, float) and pd.isna(tracklist)):
        return ""

    raw = str(tracklist).strip()
    if not raw:
        return ""

    if "\n" in raw:
        tracks = [t.strip() for t in raw.splitlines() if t.strip()]
    else:
        for sep in [";", "|", ","]:
            if sep in raw:
                tracks = [t.strip() for t in raw.split(sep) if t.strip()]
                break
        else:
            tracks = [raw]

    cleaned = []
    for t in tracks:
        t = re.sub(r"^\s*(track\s*\d+)\s*[-:]\s*", "", t, flags=re.IGNORECASE)
        t = re.sub(r"^\s*\d+\.\s*", "", t)
        cleaned.append(t.strip())

    items = []
    for i, t in enumerate(cleaned, start=1):
        safe = html_lib.escape(t)
        items.append(
            f"""
            <div class="track-row">
                <div class="track-num">{i:02d}</div>
                <div class="track-title">{safe}</div>
            </div>
            """
        )

    return f'<div class="tracklist">\n{"".join(items)}\n</div>'

def find_album_cover_source(author_label: str) -> Path | None:
    """
    Find a cover image for author_label in outputs/album_covers using common extensions.
    """
    exts = [".png", ".jpg", ".jpeg", ".webp"]
    for ext in exts:
        p = ALBUM_COVERS_SRC_DIR / f"{author_label}{ext}"
        if p.exists():
            return p
    return None

def ensure_album_cover_in_docs(author_label: str) -> tuple[bool, str, str]:
    """
    Ensures cover exists in docs/assets/album_covers/ (copies if needed).
    Returns:
      (ok, rel_from_author_page, rel_from_docs_root)

    - rel_from_author_page used on docs/authors/<author>.html
    - rel_from_docs_root used on docs/index.html browse cards
    """
    src = find_album_cover_source(author_label)
    if src is None:
        build_report.append((author_label, "missing_album_cover", f"no file in {ALBUM_COVERS_SRC_DIR}"))
        return False, "", ""

    dst = COVERS_DIR / src.name
    try:
        # Copy only if missing or stale
        if (not dst.exists()) or (dst.stat().st_mtime < src.stat().st_mtime):
            shutil.copy2(src, dst)
    except Exception as e:
        build_report.append((author_label, "album_cover_copy_failed", repr(e)))
        return False, "", ""

    if not dst.exists():
        build_report.append((author_label, "album_cover_copy_missing_dst", str(dst)))
        return False, "", ""

    # From docs/authors/<author>.html to docs/assets/album_covers/<file>
    rel_author = f"../assets/album_covers/{html_lib.escape(dst.name)}"
    # From docs/index.html to docs/assets/album_covers/<file>
    rel_root = f"assets/album_covers/{html_lib.escape(dst.name)}"
    return True, rel_author, rel_root

def album_cover_block(author_label: str, artist_name_raw: str, album_title_raw: str) -> str:
    ok, rel_from_author, _rel_from_root = ensure_album_cover_in_docs(author_label)
    if not ok:
        return """
        <div class="cover-placeholder">
          Album cover art not available yet.
        </div>
        """
    alt = html_lib.escape(f"Album cover for {artist_name_raw} — {album_title_raw}".strip(" —"))
    return f"""
      <div class="cover-wrap">
        <img class="album-cover" src="{rel_from_author}" alt="{alt}" loading="lazy">
      </div>
    """

# ----------------------------
# PRE-NORMALIZE KEYS
# ----------------------------

summary_df["author_label"] = summary_df["author_file"].apply(canonical_author_label)

if "author_label" not in persona_df.columns:
    raise ValueError("Persona CSV is missing required column: author_label")

persona_df["author_label"] = persona_df["author_label"].apply(canonical_author_label)

summary_by_label = {
    row["author_label"]: row
    for _, row in summary_df.iterrows()
    if row.get("author_label")
}
persona_by_label = {
    row["author_label"]: row
    for _, row in persona_df.iterrows()
    if row.get("author_label")
}

# ----------------------------
# HTML STYLE (author pages)
# ----------------------------

PAGE_STYLE = """
<style>
:root{
  --bg1:#f6f8ff;
  --bg2:#eef3ff;

  --card:#ffffff;
  --card2:#f3f6ff;

  --text:#1e293b;
  --muted:#64748b;

  --accent:#c5b358;      /* Vanderbilt gold */
  --accent2:#6366f1;     /* spring purple */

  --shadow:0 10px 25px rgba(0,0,0,.08);
  --radius:18px;
}

* { box-sizing: border-box; }

body{
  font-family: Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;
  margin:0;
  color:var(--text);

  background:
    radial-gradient(900px 600px at 10% 10%, rgba(99,102,241,.10), transparent 60%),
    radial-gradient(900px 600px at 90% 20%, rgba(197,179,88,.10), transparent 60%),
    linear-gradient(180deg, var(--bg1), var(--bg2));
}

.container{
  max-width: 980px;
  margin: 0 auto;
  padding: 44px 20px 60px;
}

.hero{
  position: relative;
  padding:28px;
  border-radius:var(--radius);
  background:linear-gradient(135deg, #ffffff, #f4f7ff);
  border:1px solid rgba(0,0,0,.06);
  box-shadow:var(--shadow);
  overflow: hidden;
}

.hero::after{
  content:"";
  position:absolute;
  right:-140px;
  top:-140px;
  width: 320px;
  height: 320px;
  background: radial-gradient(circle at center, rgba(56,189,248,.30), transparent 60%);
  transform: rotate(20deg);
}

.kicker{
  color: var(--muted);
  font-weight: 600;
  letter-spacing: .04em;
  text-transform: uppercase;
  font-size: 12px;
}

h1{
  font-size: 44px;
  margin: 8px 0 6px;
  line-height: 1.05;
}

.subtitle{
  color: var(--muted);
  font-size: 15px;
  margin: 0;
  max-width: 70ch;
}

.section{
  margin-top:22px;
  padding:22px;
  border-radius:var(--radius);
  background:var(--card);
  border:1px solid rgba(0,0,0,.05);
  box-shadow:var(--shadow);
}

.section h2{
  margin: 0 0 14px;
  color: var(--accent);
  font-size: 26px;
  letter-spacing: .01em;
}

.grid{
  display:grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 14px;
}

/* Make Top Journal / Top Paper main text white */
.card .small b {
  color: var(--text);
}

/* Keep the rest of the small text muted */
.card .small {
  color: var(--muted);
}

.card{
  background:var(--card2);
  border:1px solid rgba(0,0,0,.05);
  border-radius:16px;
  padding:16px;
}

.card .label{
  color: var(--muted);
  font-size: 12px;
  font-weight: 700;
  letter-spacing: .04em;
  text-transform: uppercase;
  margin-bottom: 8px;
}

.card .value{
  font-size: 26px;
  font-weight: 800;
}

.card .small b{
  color:var(--text);
  font-weight:700;
}

.pill{
  display:inline-block;
  padding: 6px 10px;
  border-radius: 999px;
  background: rgba(56,189,248,.14);
  border: 1px solid rgba(56,189,248,.25);
  color: var(--accent);
  font-weight: 700;
  font-size: 12px;
}

.album-card{
  border-radius: var(--radius);
  padding: 18px;
  background: linear-gradient(135deg, rgba(56,189,248,.12), rgba(167,139,250,.12));
  border: 1px solid rgba(255,255,255,.10);
}

.artist{
  font-size: 22px;
  font-weight: 900;
  margin: 0 0 10px;
}

.bio{
  color: var(--muted);
  line-height: 1.55;
  margin: 0 0 14px;
}

.album-title{
  display:flex;
  align-items:center;
  gap:10px;
  margin: 0 0 12px;
  font-size: 18px;
  font-weight: 900;
}

.album-title span{
  color: var(--accent2);
}

/* Album cover block (Spotify-ish) */
.cover-wrap{
  display:flex;
  justify-content:center;
  margin: 14px 0 14px;
}

.album-cover{
  width: 340px;
  max-width: 100%;
  height: auto;
  border-radius: 16px;
  box-shadow: 0 18px 45px rgba(0,0,0,.18);
  border: 1px solid rgba(255,255,255,.25);
  background: rgba(255,255,255,.25);
}

/* Placeholder that prevents broken image icons */
.cover-placeholder{
  display:flex;
  justify-content:center;
  align-items:center;
  margin: 14px 0 14px;
  padding: 16px;
  border-radius: 16px;
  border: 1px dashed rgba(100,116,139,.5);
  color: var(--muted);
  background: rgba(255,255,255,.35);
  font-weight: 650;
}

.tracklist{
  border-radius: 14px;
  overflow: hidden;
  border: 1px solid rgba(255,255,255,.10);
  background: rgba(0,0,0,.12);
}

.track-row{
  display:flex;
  gap: 14px;
  padding: 12px 14px;
  align-items:center;
  border-bottom: 1px solid rgba(255,255,255,.08);
}

.track-row:last-child{ border-bottom: none; }

.track-num{
  width: 44px;
  color: rgba(255,255,255,.65);
  font-weight: 800;
  font-variant-numeric: tabular-nums;
}

.track-title{
  font-weight: 650;
}

.footer-note{
  color: var(--muted);
  line-height: 1.5;
}

@media (max-width: 760px){
  .grid{ grid-template-columns: 1fr; }
  h1{ font-size: 36px; }
  .album-cover{ width: 320px; }
}
</style>
"""

# ----------------------------
# AUTHOR PAGE GENERATION
# ----------------------------

def generate_author_page(author_label: str):
    author_label = canonical_author_label(author_label)
    first, last = parse_author_name(author_label)

    # -------- Summary --------
    row = summary_by_label.get(author_label)
    if row is None:
        build_report.append((author_label, "missing_summary_row", f"searched label={author_label}"))
        pub = ""
        cit = ""
        top_journal = ""
        top_paper = ""
        top_paper_cit = ""
    else:
        pub = row.get("pub_count_2025_present", "")
        cit = row.get("citation_count_2025_present", "")
        top_journal = row.get("top_journal_2025_present", "")
        top_paper = row.get("top_paper_title_2025_present", "")
        top_paper_cit = row.get("top_paper_citations_2025_present", "")

    top_journal_safe = html_lib.escape(str(top_journal or ""))
    top_paper_safe = html_lib.escape(str(top_paper or ""))

    summary_html = f"""
    <div class="grid">
      <div class="card">
        <div class="label">Publications (2025–Present)</div>
        <div class="value">{pub}</div>
      </div>

      <div class="card">
        <div class="label">Citations (2025–Present)</div>
        <div class="value">{cit}</div>
      </div>

      <div class="card">
        <div class="label">Top Journal</div>
        <div class="small"><b>{top_journal_safe}</b></div>
      </div>

      <div class="card">
        <div class="label">Top Paper</div>
        <div class="small"><b>{top_paper_safe}</b><br>
        <span class="pill">Citations: {top_paper_cit}</span>
        </div>
      </div>
    </div>
    """

    # -------- Persona --------
    p = persona_by_label.get(author_label)
    if p is None:
        build_report.append((author_label, "missing_persona_row", f"searched label={author_label}"))
        persona_html = "<p class='footer-note'>No persona generated.</p>"
    else:
        status_val = str(p.get("status", "")).strip()
        if status_val and status_val.lower() != "ok":
            build_report.append((author_label, "persona_status", status_val))

        artist_name_raw = str(p.get("artist_name", "") or "")
        album_title_raw = str(p.get("album_title", "") or "")

        artist_name = html_lib.escape(artist_name_raw)
        persona_bio = html_lib.escape(str(p.get("persona_bio", "") or "")).replace("\n", "<br>")
        album_title = html_lib.escape(album_title_raw)

        cover_block = album_cover_block(author_label, artist_name_raw, album_title_raw)
        tracklist_html = format_tracklist(p.get("tracklist", ""))

        persona_html = f"""
        <div class="album-card">
          <div class="artist">{artist_name}</div>
          <p class="bio">{persona_bio}</p>

          <div class="album-title">Album: <span>{album_title}</span></div>

          {cover_block}

          {tracklist_html}
        </div>
        """

    # -------- Build Page --------
    page_html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{first} {last} • VALIANT Wrapped</title>
{PAGE_STYLE}
</head>

<body>
<div class="container">

  <div class="hero">
    <div class="kicker">VALIANT Wrapped • 2025–2026</div>
    <h1>{first} {last}</h1>
    <p class="subtitle">
      A year-in-review snapshot of publications, citations, and a fictional musical persona inspired by your work.
    </p>
  </div>

  <div class="section">
    <h2>2025–2026 Stats</h2>
    {summary_html}
  </div>

  <div class="section">
    <h2>Your Musical Persona</h2>
    <p class="footer-note">
      People like you are what make our discovery center so vibrant and unique.
      To celebrate your work, we created a fictional musical persona inspired by your publishing history.
    </p>
    {persona_html}
  </div>

  <div class="section">
    <h2>Thank You</h2>
    <p class="footer-note">
      Thank you for being part of our discovery center and for contributing to another incredible year of innovation and collaboration.
    </p>
  </div>

</div>
</body>
</html>
"""
    (AUTHOR_DIR / f"{author_label}.html").write_text(page_html, encoding="utf-8")

# ----------------------------
# GENERATE AUTHOR PAGES
# ----------------------------

authors = summary_df["author_label"].dropna().astype(str).unique()
for author_label in authors:
    generate_author_page(author_label)

# ----------------------------
# OPTION A ADDITIONS:
# 1) write docs/data/authors.json
# 2) write docs/assets/styles.css + app.js
# 3) write Spotify-ish docs/index.html
# ----------------------------

BROWSE_CSS = r"""
:root{
  --bg:#0b0b0f;
  --panel:#12121a;
  --panel2:#171722;
  --text:#f2f2f2;
  --muted:#b7b7c7;
  --accent:#24d06f;
  --stroke:#2a2a3a;
  --shadow: 0 10px 30px rgba(0,0,0,.35);
  --radius: 18px;
  --radius2: 24px;
  --font: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial;
}
*{box-sizing:border-box}
html,body{height:100%}
body{
  margin:0;
  background:linear-gradient(180deg, #08080c 0%, var(--bg) 60%);
  color:var(--text);
  font-family:var(--font);
}
.app{
  display:grid;
  grid-template-columns: 280px 1fr;
  min-height:100vh;
}
.sidebar{
  padding:18px;
  background:linear-gradient(180deg, #0c0c12 0%, #07070b 100%);
  border-right:1px solid var(--stroke);
}
.brand{
  display:flex;
  gap:12px;
  align-items:center;
  padding:12px;
  border-radius:var(--radius);
  background:rgba(255,255,255,0.03);
  border:1px solid rgba(255,255,255,0.06);
}
.logo{
  width:44px;height:44px;border-radius:14px;
  background:radial-gradient(circle at 30% 30%, var(--accent) 0%, rgba(36,208,111,.0) 55%),
             linear-gradient(135deg, #2c2cff 0%, #15151f 55%, #ff2c7a 110%);
  box-shadow: var(--shadow);
}
.brandTitle{font-weight:700; letter-spacing:.2px;}
.brandSub{font-size:12px;color:var(--muted); margin-top:2px;}
.nav{margin-top:16px; display:flex; flex-direction:column; gap:8px;}
.navItem{
  text-decoration:none;
  color:var(--muted);
  padding:10px 12px;
  border-radius:14px;
  border:1px solid transparent;
}
.navItem:hover{background:rgba(255,255,255,0.04); color:var(--text);}
.navItem.active{
  background:rgba(36,208,111,0.10);
  border-color:rgba(36,208,111,0.25);
  color:var(--text);
}
.sidebarFooter{margin-top:18px; padding:12px; color:var(--muted); font-size:12px;}
.main{padding:18px;}
.topbar{
  display:flex;
  gap:12px;
  align-items:center;
  position:sticky;
  top:0;
  padding:12px 0 16px 0;
  background:linear-gradient(180deg, rgba(11,11,15,1) 0%, rgba(11,11,15,.75) 70%, rgba(11,11,15,0) 100%);
  backdrop-filter: blur(10px);
  z-index:5;
}
.search,.filter{
  border-radius: 999px;
  padding:12px 14px;
  border:1px solid var(--stroke);
  background:rgba(255,255,255,0.04);
  color:var(--text);
  outline:none;
}
.search{flex:1}
.search::placeholder{color:rgba(242,242,242,.45)}
.sectionTitle{
  font-size:22px;
  font-weight:800;
  margin:10px 0 14px 0;
}
.grid{
  display:grid;
  grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
  gap:14px;
}
.card{
  background:linear-gradient(180deg, rgba(255,255,255,0.04) 0%, rgba(255,255,255,0.02) 100%);
  border:1px solid rgba(255,255,255,0.06);
  border-radius:var(--radius2);
  padding:14px;
  cursor:pointer;
  box-shadow: none;
  transition: transform .12s ease, box-shadow .12s ease, border-color .12s ease;
  text-decoration:none;
  color:inherit;
}
.card:hover{
  transform: translateY(-2px);
  box-shadow: var(--shadow);
  border-color:rgba(255,255,255,0.14);
}
.cover{
  width:100%;
  aspect-ratio: 1/1;
  border-radius:18px;
  background: linear-gradient(135deg, rgba(36,208,111,.35), rgba(44,44,255,.25), rgba(255,44,122,.22));
  border:1px solid rgba(255,255,255,0.08);
  overflow:hidden;
}
.cover img{width:100%; height:100%; object-fit:cover; display:block;}
.meta{margin-top:12px}
.name{font-weight:800; font-size:16px; line-height:1.1}
.sub{color:var(--muted); font-size:12px; margin-top:6px; line-height:1.3}
.tags{
  display:flex; flex-wrap:wrap; gap:6px;
  margin-top:10px;
}
.tag{
  font-size:11px;
  color:rgba(242,242,242,.85);
  padding:6px 10px;
  border-radius:999px;
  border:1px solid rgba(255,255,255,0.10);
  background:rgba(255,255,255,0.03);
}
.empty{color:var(--muted); padding:20px 4px;}
.hidden{display:none;}
@media (max-width: 860px){
  .app{grid-template-columns: 1fr;}
  .sidebar{position:sticky; top:0; z-index:10;}
}
"""

BROWSE_JS = r"""
async function loadAuthors() {
  const res = await fetch("data/authors.json");
  if (!res.ok) throw new Error("Failed to load data/authors.json");
  return await res.json();
}

function uniq(arr) {
  return Array.from(new Set(arr)).sort((a,b) => a.localeCompare(b));
}

function norm(s) {
  return (s || "").toString().toLowerCase();
}

function matches(author, q, theme) {
  if (theme && !(author.themes || []).includes(theme)) return false;
  if (!q) return true;

  const hay = [
    author.display_name,
    author.author_label,
    author.artist_name,
    author.album_title,
    (author.themes || []).join(" "),
    author.top_journal,
    author.top_paper
  ].join(" ");

  return norm(hay).includes(norm(q));
}

function cardHTML(a) {
  const tags = (a.themes || []).slice(0, 3).map(t => `<span class="tag">${escapeHtml(t)}</span>`).join("");
  const sub = [
    a.artist_name ? `Artist: ${escapeHtml(a.artist_name)}` : "",
    a.album_title ? `Album: ${escapeHtml(a.album_title)}` : ""
  ].filter(Boolean).join(" • ");

  const cover = a.cover_url
    ? `<img src="${a.cover_url}" alt="" loading="lazy" />`
    : "";

  return `
    <a class="card" href="${a.profile_url}">
      <div class="cover">${cover}</div>
      <div class="meta">
        <div class="name">${escapeHtml(a.display_name || a.author_label)}</div>
        <div class="sub">${sub || "&nbsp;"}</div>
        <div class="tags">${tags}</div>
      </div>
    </a>
  `;
}

function escapeHtml(str) {
  return (str || "").toString()
    .replaceAll("&","&amp;")
    .replaceAll("<","&lt;")
    .replaceAll(">","&gt;")
    .replaceAll('"',"&quot;")
    .replaceAll("'","&#039;");
}

function render(authors, q, theme) {
  const grid = document.getElementById("grid");
  const empty = document.getElementById("empty");

  const filtered = authors.filter(a => matches(a, q, theme));
  grid.innerHTML = filtered.map(cardHTML).join("");

  empty.classList.toggle("hidden", filtered.length !== 0);
}

function fillThemeFilter(authors) {
  const sel = document.getElementById("themeFilter");
  const allThemes = uniq(authors.flatMap(a => a.themes || []).filter(Boolean));
  if (allThemes.length === 0) {
    // hide filter if no themes exist
    sel.classList.add("hidden");
    return;
  }
  for (const t of allThemes) {
    const opt = document.createElement("option");
    opt.value = t;
    opt.textContent = t;
    sel.appendChild(opt);
  }
}

(async function init() {
  const authors = await loadAuthors();
  fillThemeFilter(authors);

  const search = document.getElementById("search");
  const themeFilter = document.getElementById("themeFilter");

  const rerender = () => render(authors, search.value, themeFilter.value);

  search.addEventListener("input", rerender);
  themeFilter.addEventListener("change", rerender);

  rerender();
})();
"""

def write_browse_assets():
    (BROWSE_ASSET_DIR / "styles.css").write_text(BROWSE_CSS.strip() + "\n", encoding="utf-8")
    (BROWSE_ASSET_DIR / "app.js").write_text(BROWSE_JS.strip() + "\n", encoding="utf-8")

def build_authors_json(authors_list: list[str]):
    """
    Build docs/data/authors.json for the browse homepage.
    Uses:
      - summary_df (pubs/cites/top journal/paper + optional themes if present)
      - persona_df (artist_name/album_title)
      - cover assets if present (copied into docs/assets/album_covers)
    """
    # Optional themes columns you might have (supports several likely names)
    theme_cols = [c for c in ["themes", "theme_list", "research_themes", "top_themes"] if c in summary_df.columns]

    records = []
    for a in authors_list:
        a = canonical_author_label(a)
        if not a:
            continue

        # ensure cover is copied (so browse page can show it if available)
        ok_cover, _rel_author, rel_root = ensure_album_cover_in_docs(a)
        cover_url = rel_root if ok_cover else ""

        # summary fields
        row = summary_by_label.get(a, {})
        top_journal = row.get("top_journal_2025_present", "") if isinstance(row, dict) else row.get("top_journal_2025_present", "")
        top_paper = row.get("top_paper_title_2025_present", "") if isinstance(row, dict) else row.get("top_paper_title_2025_present", "")

        # themes (optional)
        themes = []
        if theme_cols and not isinstance(row, dict):
            # if it's a pandas Series
            for c in theme_cols:
                themes = safe_split_themes(row.get(c, ""))
                if themes:
                    break
        elif theme_cols and isinstance(row, dict):
            for c in theme_cols:
                themes = safe_split_themes(row.get(c, ""))
                if themes:
                    break

        # persona fields
        p = persona_by_label.get(a)
        artist_name = ""
        album_title = ""
        if p is not None:
            artist_name = str(p.get("artist_name", "") or "")
            album_title = str(p.get("album_title", "") or "")

        records.append({
            "author_label": a,
            "display_name": display_name_from_label(a),
            "artist_name": artist_name,
            "album_title": album_title,
            "themes": themes,
            "top_journal": "" if pd.isna(top_journal) else str(top_journal),
            "top_paper": "" if pd.isna(top_paper) else str(top_paper),
            "profile_url": f"authors/{a}.html",
            "cover_url": cover_url
        })

    records.sort(key=lambda r: (r.get("display_name") or r.get("author_label") or "").lower())

    out_path = DATA_DIR / "authors.json"
    out_path.write_text(json.dumps(records, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

def write_browse_index():
    index_html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>VALIANT Wrapped — Browse</title>
  <link rel="stylesheet" href="assets/styles.css" />
</head>
<body>
  <div class="app">
    <aside class="sidebar">
      <div class="brand">
        <div class="logo"></div>
        <div class="brandText">
          <div class="brandTitle">VALIANT Wrapped</div>
          <div class="brandSub">Browse profiles</div>
        </div>
      </div>

      <nav class="nav">
        <a class="navItem active" href="index.html">Home</a>
        <a class="navItem" href="#" onclick="return false;">Browse</a>
        <a class="navItem" href="#" onclick="return false;">About</a>
      </nav>

      <div class="sidebarFooter">
        <div class="hint">
          Generated: {html_lib.escape(now_iso())}<br>
          Published folder: {html_lib.escape(str(DOCS_DIR))}
        </div>
      </div>
    </aside>

    <main class="main">
      <header class="topbar">
        <input id="search" class="search" placeholder="Search authors, themes, albums…" />
        <select id="themeFilter" class="filter">
          <option value="">All themes</option>
        </select>
      </header>

      <section class="section">
        <div class="sectionTitle">Authors</div>
        <div id="grid" class="grid"></div>
        <div id="empty" class="empty hidden">No matches. Try a different search.</div>
      </section>
    </main>
  </div>

  <script src="assets/app.js"></script>
</body>
</html>
"""
    (DOCS_DIR / "index.html").write_text(index_html, encoding="utf-8")

# write browse UI assets + authors.json + index.html
write_browse_assets()
build_authors_json(list(authors))
write_browse_index()

# ----------------------------
# BUILD REPORT
# ----------------------------

report_path = DOCS_DIR / "build_report.csv"
report_df = pd.DataFrame(build_report, columns=["author_label", "issue", "details"])
report_df.to_csv(report_path, index=False, encoding="utf-8")

print("Site generation complete.")
print(f"Published to: {DOCS_DIR}")
print(f"Browse page: {DOCS_DIR / 'index.html'}")
print(f"Authors JSON: {DATA_DIR / 'authors.json'}")
print(f"Check {report_path} for issues.")
print(f"Album cover assets copied to: {COVERS_DIR}")
